version: "3"

services:
  watchtower:
    container_name: "watchtower"
    image: "containrrr/watchtower:arm64v8-latest"
    restart: "unless-stopped"
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_ROLLING_RESTART=false
      - WATCHTOWER_SCHEDULE="0 0 4 * * sat"
      - WATCHTOWER_TIMEOUT="100s"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - dockeronly
      - internet

networks:
  dockeronly:
    name: "dockeronly"
    internal: true
    attachable: true
  internet:
    name: "internet"
