version: "3.5"

services:
  watchtower:
    container_name: "watchtower"
    image: "containrrr/watchtower:latest"
    restart: "unless-stopped"
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_ROLLING_RESTART=false
      - WATCHTOWER_SCHEDULE="0 0 4 * * sat"
      - WATCHTOWER_TIMEOUT="100s"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - internet

networks:
  internet:
    name: "internet"
