version: "3.3"

services:
  gitea:
    container_name: "gitea"
    image: "gitea/gitea:1.20"
    restart: "unless-stopped"
    environment:
      - USER_UID=1000
      - USER_GID=1000
    expose:
      - "3000"
    ports:
      - "22:22"
    volumes:
      - "/data/gitea:/data"
    networks:
      - dockeronly
      - internet

networks:
  dockeronly:
    name: "dockeronly"
    internal: true
    attachable: true
  internet:
    name: "internet"

