version: "3.5"

services:
  gitea:
    container_name: "gitea"
    image: "gitea/gitea:latest"
    restart: "unless-stopped"
    environment:
      - USER_UID=1000
      - USER_GID=1000
    expose:
      - "3000"
    ports:
      - "22:22"
    volumes:
      - "/data/gitea:/data"
    networks:
      - internet

networks:
  internet:
    name: "internet"

