# https://old.reddit.com/r/jellyfin/comments/ei6ew6/rpi4_hardware_acceleration_guide/
# potentially something we could try in the future
version: "3.5"

services:
  jellyfin:
    container_name: "jellyfin"
    image: "jellyfin/jellyfin:10"
    restart: "unless-stopped"
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=Europe/Berlin
    expose:
      - "8096"
      - "8920"
    ports:
      - "1900:1900/udp"
      - "7359:7359/udp"
    volumes:
      - "/data/jellyfin/config:/config"
      - "/data/jellyfin/cache:/cache"
      - "/data/media:/media"
    networks:
      - internet

networks:
  internet:
    name: "internet"
