version: "3.3"

services:
  jellyfin:
    container_name: "jellyfin"
    image: "jellyfin/jellyfin:latest"
    restart: "unless-stopped"
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=Europe/Berlin
    expose:
      - "8096"
      - "8920"
    ports:
      - "1900:1900/udp"
      - "7359:7359/udp"
    volumes:
      - "/data/jellyfin/config:/config"
      - "/data/jellyfin/cache:/cache"
      - "/data/media:/media"
    networks:
      - dockeronly
      - internet

networks:
  dockeronly:
    name: "dockeronly"
    internal: true
    attachable: true
  internet:
    name: "internet"
