version: '3.3'
services:
  stirling-pdf:
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest
    container_name: stirlingpdf
    restart: unless-stopped
    expose:
      - 8080
    volumes:
      - /data/StirlingPDF/trainingData:/usr/share/tessdata # Required for extra OCR languages
      - /data/StirlingPDF/extraConfigs:/configs
      - /data/StirlingPDF/customFiles:/customFiles/
      - /data/StirlingPDF/logs:/logs/
      - /data/StirlingPDF/pipeline:/pipeline/
    environment:
      - DISABLE_ADDITIONAL_FEATURES=false
      - JAVA_TOOL_OPTIONS="-Xms100m -Xmx300m"  # Min 512MB, Max 4GB RAM
      - LANGS=en_GB
    deploy:
      resources:
        limits:
          memory: '500M'
    networks:
      - dockeronly

networks:
  dockeronly:
    name: "dockeronly"
    internal: true
    attachable: true
