version: '3.8'

services:
  kuma:
    container-name: "kuma"
    image: "louislam/uptime-kuma:1"
    restart: "unless-stopped"
    volumes:
      - "/data/kuma:/app/data"
    expose:
      - 3001
    networks:
      - dockeronly
      - internet

networks:
  dockeronly:
    name: "dockeronly"
    internal: true
    attachable: true
  internet:
    name: "internet"
