
services:
  prometheus_pv:
    container_name: "prometheus_pv"
    image: "prom/prometheus:latest"
    restart: "unless-stopped"
    expose:
      - 9090
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=10y"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml:ro"
      - "/data/prometheus_pv:/prometheus"
    networks:
      - internet
      - dockeronly

networks:
  dockeronly:
    name: "dockeronly"
    internal: true
    attachable: true
  internet:
    name: "internet"

