version: "3.5"

services:
  caddy:
    container_name: "caddy"
    image: "caddy:2.6"
    restart: "unless-stopped"
    env_file: 
      - ".env"  # HOSTNAME
    ports:
    - "80:80"
    - "443:443"
    - "443:443/udp"
    volumes:
      - "/data/caddy/data:/data"
      - "/data/caddy/config:/config"
      - "./Caddyfile:/etc/caddy/Caddyfile"
    networks:
      - internet

networks:
  internet:
    name: "internet"
